apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: ninoverhaegh/userservice:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
